version: '3.4'

services:
  ci-build:
    image: mcr.microsoft.com/dotnet/core/sdk:3.1
    volumes:
      - .:/src
    working_dir: /src
    command: /bin/bash -c "dotnet restore ./MyCommunity.sln && dotnet publish ./MyCommunity.sln -c Release -o ./obj/Docker/publish"
    